before:
  hooks:
    - go mod download
builds:
- binary: bin/entrypoint
  env:
  - CGO_ENABLED=0
  goos:
    - aix
    #- android
    - darwin
    - dragonfly
    - freebsd
    - illumos
    - js
    - linux
    - netbsd
    - openbsd
    - plan9
    - solaris
    - windows
  goarch:
    - 386
    - amd64
    - amd64p32
    - arm
    - arm64
    - mips
    - mips64
    - mips64le
    - mipsle
    - ppc64
    - ppc64le
    - s390x
    - wasm
  goarm:
    - 5
    - 6
    - 7
  targets:
    - aix_ppc64
    - darwin_386
    - darwin_amd64
    - dragonfly_amd64
    - freebsd_386
    - freebsd_amd64
    - freebsd_arm
    - illumos_amd64
    - js_wasm
    - linux_386
    - linux_amd64
    - linux_arm_5
    - linux_arm_6
    - linux_arm_7
    - linux_arm64
    - linux_mips
    - linux_mips64
    - linux_mips64le
    - linux_mipsle
    - linux_ppc64
    - linux_ppc64le
    - linux_s390x
    - nacl_386
    - nacl_amd64p32
    - nacl_arm
    - netbsd_386
    - netbsd_amd64
    - netbsd_arm
    - netbsd_arm64
    - openbsd_386
    - openbsd_amd64
    - openbsd_arm
    - openbsd_arm64
    - plan9_386
    - plan9_amd64
    - plan9_arm
    - solaris_amd64
    - windows_386
    - windows_amd64
    - windows_arm
    
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
